---
title: Nathan Albrecht Portfolio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  thoughts:
    title: Thoughts
    output: false
  uploads:
    title: Uploads
    output: true
